[versions]
kotlin = "2.2.21"

[libraries]
# Library
compose-ui = "androidx.compose.ui:ui:1.9.4"
compose-material = "androidx.compose.material:material:1.9.4"
androidx-core = "androidx.core:core-ktx:1.17.0"
playServices-wallet = "com.google.android.gms:play-services-wallet:19.5.0"

# Sample/App
sample-compose-ui-tooling = "androidx.compose.ui:ui-tooling-preview:1.9.4"
sample-compose-activity = "androidx.activity:activity-compose:1.11.0"

[plugins]
nexusPublishingPlugin = "io.github.gradle-nexus.publish-plugin:2.0.0"
androidApplication = "com.android.application:8.13.0"
androidLibrary = "com.android.library:8.13.0"
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }